# Generated by Django 2.1.2 on 2018-10-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181029_0731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseDetails',
            new_name='HouseDetail',
        ),
    ]
